### ISSUE TITLE
Plusieurs paquets non installés dont pilotes nvidia sur configue > 12 ans

### ISSUE THREAD

**Issue by Belette01** [Cardiacman13/Architect#162]
[logfile_20231105-093503.log](https://github.com/Cardiacman13/Architect/files/13260121/logfile_20231105-093503.log)

PC Portable 12 ans d'age - comme un bon whisky !
core i7 , 8 coeurs, 15 GB de ram, Geforce 610M.

Retour nickel sur Tumbleweed ;-)

**Comment by Cardiacman13** [comment]
Re, tu avais choisi quel DE ?

**Comment by Cardiacman13** [comment]
Ah c'est bon je crois que j'ai trouvé, ton installation était pas fraiche ce genre de messages dans le log, le prouvent "kitemmodels5 et kitemmodels sont en conflit" les paquets KDE ont changé de nom.

**Comment by Cardiacman13** [comment]
Normalement c'est fix avec ce commit https://github.com/Cardiacman13/Architect/commit/749c4ebd9c5feb2054fc5d16dd39fcf56710b8b7 . Donc je ferme, tu peux re ouvrir si tu re testes et que tu as de nouveau un problème.
