### ISSUE TITLE
probleme plugins kdenlive non installer

### ISSUE THREAD

**Issue by Sakunoya** [Cardiacman13/Architect#183]
Salut Cardiac, J'ai essayer de lancé kdenlive dans le terminal et j'ai decouvert qu'il manquais les plugins d'effets et en faisant un sudo pacman -Q frei0r-plugins il m'indique pourtant en retour frei0r-plugins 2.3.1-1, je sais pas trop d'ou vient le probleme du coup j'envoie les logs si ca peut etre utile. 

Could not detect package type, probably default? App dir is "/usr/bin"
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltsdl.so
  (libSDL-1.2.so.0: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type)
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltrubberband.so
  (librubberband.so.2: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type)
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltrtaudio.so
  (librtaudio.so.6: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type)
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltmovit.so
  (libmovit.so.8: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type)
No LADSPA plugins were found!

Check your LADSPA_PATH environment variable.
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltsox.so
  (libsox.so.3: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type)
mlt_repository_init: failed to dlopen /usr/lib/mlt-7/libmltopencv.so
  (libopencv_tracking.so.408: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type)
profilePath from appDir/../share:  "/usr/share/mlt-7/profiles"
meltPath from KdenliveSetting::meltPath:  ""
meltPath from profilePath/../../../bin:  "/usr/bin/melt-7"
Empty metadata for  "telecide"
plugin not available: "avfilter.acompressor"
plugin not available: "avfilter.aecho"
plugin not available: "avfilter.agate"
plugin not available: "avfilter.atadenoise"
plugin not available: "avfilter.bwdif"
plugin not available: "avfilter.deblock"
plugin not available: "avfilter.dedot"
plugin not available: "avfilter.deflate"
plugin not available: "avfilter.derain"
plugin not available: "avfilter.doubleweave"
plugin not available: "avfilter.field"
plugin not available: "avfilter.framestep"
plugin not available: "avfilter.fspp"
plugin not available: "avfilter.graphmonitor"
plugin not available: "avfilter.hqdn3d"
plugin not available: "avfilter.inflate"
plugin not available: "avfilter.lagfun"
plugin not available: "avfilter.loudnorm"
plugin not available: "avfilter.mcdeint"
plugin not available: "avfilter.random"
plugin not available: "avfilter.removegrain"
plugin not available: "avfilter.separatefields"
plugin not available: "avfilter.shuffleplanes"
plugin not available: "avfilter.sofalizer"
plugin not available: "avfilter.sr"
plugin not available: "avfilter.tmix"
plugin not available: "avfilter.w3fdif"
plugin not available: "avfilter.weave"
plugin not available: "avfilter.yadif"
plugin not available: "frei0r.alpha0ps"
plugin not available: "frei0r.alpha0ps"
plugin not available: "frei0r.alphagrad"
plugin not available: "frei0r.alphaspot"
plugin not available: "frei0r.baltan"
plugin not available: "frei0r.bgsubtract0r"
plugin not available: "frei0r.bigsh0t_eq_mask"
plugin not available: "frei0r.bigsh0t_eq_to_rect"
plugin not available: "frei0r.bigsh0t_eq_to_stereo"
plugin not available: "frei0r.bigsh0t_hemi_to_eq"
plugin not available: "frei0r.bigsh0t_rect_to_eq"
plugin not available: "frei0r.bigsh0t_stabilize_360"
plugin not available: "frei0r.bigsh0t_transform_360"
plugin not available: "frei0r.delay0r"
plugin not available: "frei0r.delaygrab"
plugin not available: "frei0r.facebl0r"
plugin not available: "frei0r.facedetect"
plugin not available: "frei0r.hqdn3d"
plugin not available: "frei0r.lightgraffiti"
plugin not available: "frei0r.lightgraffiti"
plugin not available: "frei0r.pr0be"
plugin not available: "frei0r.pr0file"
plugin not available: "frei0r.rgbparade"
plugin not available: "frei0r.scale0tilt"
plugin not available: "frei0r.tehRoxx0r"
plugin not available: "frei0r.vectorscope"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa.9354877"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "ladspa"
plugin not available: "movit.blur"
plugin not available: "movit.sharpen"
plugin not available: "movit.diffusion"
plugin not available: "movit.flip"
plugin not available: "movit.glow"
plugin not available: "movit.lift_gamma_gain"
plugin not available: "movit.mirror"
plugin not available: "movit.opacity"
plugin not available: "movit.rect"
plugin not available: "movit.saturation"
plugin not available: "movit.unsharp_mask"
plugin not available: "movit.vignette"
plugin not available: "movit.white_balance"
plugin not available: "rbpitch"
plugin not available: "rbpitch"
plugin not available: "sox"
plugin not available: "sox"
plugin not available: "sox"
plugin not available: "sox"
plugin not available: "sox"
plugin not available: "sox"
plugin not available: "sox"
plugin not available: "timewarp"
plugin not available: "opencv.tracker"
unsupported effect in group "frei0r.alpha0ps" : "/usr/share/kdenlive/effect-templates/secondary_color_correction.xml"
Asset "mask_start-frei0r.alphaspot" has invalid dependency "frei0r.alphaspot" and is going to be removed
plugin not available: "region"
=== /// CANNOT ACCESS SPEECH DICTIONARIES FOLDER
Xlib:  extension "DRI2" missing on display ":1".
Xlib:  extension "DRI2" missing on display ":1".
QQmlEngine::setContextForObject(): Object already has a QQmlContext
QQmlEngine::setContextForObject(): Object already has a QQmlContext
QQmlEngine::setContextForObject(): Object already has a QQmlContext
QQmlEngine::setContextForObject(): Object already has a QQmlContext
Found FFMpeg binary:  "/usr/bin/ffmpeg"
==========
FOUND SUPPORTED CODECS:  ("h264_nvenc", "hevc_nvenc")
// FFMPEG ARGS:  ("-hide_banner", "-filters")
/// ++ SCALE_NPP NOT SUPPORTED
:::: NOT FOUND DOCUMENT GUIDES !!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!
QQmlEngine::setContextForObject(): Object already has a QQmlContext
qrc:/qml/timeline.qml:502: ReferenceError: proxy is not defined
qrc:/qml/timeline.qml:482: ReferenceError: proxy is not defined
==== NO PREVIOUS TIMELINE
::::::::::: connecting timeline:  QUuid("{ea11c2bc-8bb2-43df-9b70-5c59feef00fa}") , DUR:  0
root context get sub model new function
HHHHHHHHHHHH
INVALID BIN PLAYLIST...
=== OPENING FILE WITH TRACKS:  5
:::: FOUND TRACTOR WITH TRACKS:  2 

___________________________
=== MODEL DATA CHANGED: MUTE DONE TRACK NOT FOUND!!!
:::: FOUND TRACTOR WITH TRACKS:  2 

___________________________
=== MODEL DATA CHANGED: MUTE DONE TRACK NOT FOUND!!!
:::: FOUND TRACTOR WITH TRACKS:  2 

___________________________
=== MODEL DATA CHANGED: MUTE DONE TRACK NOT FOUND!!!
:::: FOUND TRACTOR WITH TRACKS:  2 

___________________________
=== MODEL DATA CHANGED: MUTE DONE TRACK NOT FOUND!!!
===== ACTIVATING DOCUMENT:  QUuid("{ea11c2bc-8bb2-43df-9b70-5c59feef00fa}") 
::::::::::::::::::::::
==== NO PREVIOUS TIMELINE
==== ABORTING NO TIMELINE AVAILABLE
::::::==

**Comment by Cardiacman13** [comment]
Il y a toujours des erreurs dans le terminal sur quasiment tous les logiciels et toutes les distros. C'est comme les erreurs kernels c'est à ignorer si au final ça fonctionne. Ça fonctionne ?

**Comment by Cardiacman13** [comment]
J'ai fais quelques tests ce matin j'ai la même "erreur" dans le terminal, mais Kdenlive fonctionne parfaitement bien. Pour moi c'est à ignorer ce genre de choses. Si on cherche sur google cette erreur s'affiche au moins depuis 2022 dans le terminal et n’empêche pas Kdenlive de fonctionner parfaitement.
