### ISSUE TITLE
Erreur lors de l'installation de vivaldi et vs code

### ISSUE THREAD

**Issue by Fea99** [Cardiacman13/Architect#214]
Petite erreur dans le script lors de l'install de vivaldi et visual studio code 
Il colle ensemble "vivaldi-ffmpeg-codecs" et "visual-studio-code-bin"

![Screenshot_20231127_210641](https://github.com/Cardiacman13/Architect/assets/13392574/caa1d48c-83c3-4bb0-9047-78767a0f86e7)

Log complet : 
https://0x0.st/Hw5n.log

**Comment by Neo-29** [comment]
![IMG_20231128_141554](https://github.com/Cardiacman13/Architect/assets/90937180/4f51a414-8d85-4dd0-b87c-657074aa1f4c)
vivaldi-ffmpeg-codecsvisual-studio-code-bin

Ce paquet n'existe nulle part sur Archlinux.

**Comment by Neo-29** [comment]
![IMG_20231128_141554](https://github.com/Cardiacman13/Architect/assets/90937180/7bda4735-47be-4ef0-90b7-533d962d7ee5)

Le pb est là oui.

**Comment by Cardiacman13** [comment]
On est saisi du problème, il y a un moyen de fixer ça rapidement en mettant un espace à la fin du nom des paquets dans le script. Mais je préfère attendre que mon collègue s'en charge car je pense qu'il a moyen de faire ça plus proprement.

**Comment by Cardiacman13** [comment]
C'est fix: https://github.com/Cardiacman13/Architect/commit/e9149071f13def8a5ef84ec1e2062a69e40c6523
