### ISSUE TITLE
Résolutions de conflits de paquets

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Architect#215]
**Description**
Si j'utilise le script de rawleenc, j'ai déjà exfatprogs installé. Ca fait un conflit avec exfat-utils insolluble, provocant une erreur, qui n'en est pas une.

**Steps to Reproduce**
1- Installer arch avec script rawleenc
2- Exécuter architect

**Expected Behavior**
Ne pas avoir "Erreur - installation failed" en cas de conflit, Mais un message plus explicite "Conflit détecté : proposer ou pas la résolution manuelle", ou un simple commentaire précisant que le paquet déjà présent reste inchangé

**Actual Behavior**
Mesage d'erreur : Installation failed

**Screenshots/Logs**
![Screenshot_20231129_131424](https://github.com/Cardiacman13/Architect/assets/66792063/213fc361-498c-425f-80a2-c3380e71ddb1)

**System Information**
Arch - Rawleenc install script

**Comment by Cardiacman13** [comment]
Là pour le coup je refuse c'est trop de travail script compatible avec Arch install uniquement comme précisé dans la doc.
