### ISSUE TITLE
Supprimer l'icône hp-uiscan dégueulasse et inutile

### ISSUE THREAD

**Issue by Xdavius** [Cardiacman13/Architect#217]
NE RIEN FAIRE POUR L'INSTANT

ajouter : 

```sudo xdg-desktop-menu install /usr/share/desktop-directories/kf5-utilities.directory /usr/share/applications/hp-uiscan.desktop```
```sudo rm /usr/share/applications/hp-uiscan.desktop```

Je cherche encore une bonne solution, si elle existe =)

**Comment by Cardiacman13** [comment]
Dav, si tu me trouves la solution pour virer le raccourcis de discover je te fais un bisous.

**Comment by Cardiacman13** [comment]
Trop du detail ce n'est pas vraiment une issue, plutôt à discuter dans : https://github.com/Cardiacman13/Architect/discussions
