### ISSUE TITLE
VA-API  et/ou VDPAU

### ISSUE THREAD

**Issue by jbreizh** [Cardiacman13/Architect#223]
Hello,
il me semble qu'il n'y a rien dans ton script pour l'accélération matérielle  des vidéos comme décrit ici :

https://wiki.archlinux.org/title/Hardware_video_acceleration

Bon ça ne fait pas une diff flagrante sur un pc gamer, mais bon les paquets ne sont pas gros...

**Comment by Cardiacman13** [comment]
Hello,
Merci du retour,

J'installe ça pour AMD https://github.com/Cardiacman13/Architect/blob/main/src/system/drivers/amd.sh et ça https://github.com/Cardiacman13/Architect/blob/main/src/system/drivers/intel.sh pour intel.

Il me semble qu'il y a tout si tu veux bien jeter un coup d’œil :)

**Comment by jbreizh** [comment]
Rapide !!!
Perso je n'ai installé que VA-API sur ma config full AMD. Après je suis loin d'être sur de moi, mais de ma compréhension VA-API et VDPAU font la même chose, mais VDPAU est une techno Nvidia. Donc même si on peut mettre VDPAU sur intel et AMD, je dirais que VA-API est mieux pour intel et AMD et VDPAU est mieux pour Nvidia. Bref pas sur qu'il soit utile d'installer les 2, mais à confirmer avec des gens plus calé que moi...

**Comment by Cardiacman13** [comment]
@Xdavius Un avis sur la question mon Dav ? Perso avec Nvidia je ne me pose pas trop la question.

**Comment by Cardiacman13** [comment]
> Tu as ajouté vaapi mesa et vdpau mesa pour AMD et Intel ?
> 
> C'est les mêmes paquets que demandait vinceff de toute façon pour l'encodage sur OBS .
> 
> Pour moi il les faut. C'est encodage/décodage.
> 
> Pour Nvidia normalement tu installes Nvidia-vaapi et ça doit être inclus dans le driver.
> 
> Mais personnellement, je fais tout avec mon CPU. La mise en place du décodage GPU hormis sur Firefox et VLC c'est trop casse burne.

Normalement oui c'est bon, regarde les fichiers intel.sh et amd.sh

**Comment by Cardiacman13** [comment]
J'ai mis vaapi pour tout le monde.

https://github.com/Cardiacman13/Architect/commit/506ee44795a8639151a551e34b7baaa0fafeddcf
