### ISSUE TITLE
Graphiques hybrides

### ISSUE THREAD

**Issue by Kadnix** [Cardiacman13/Architect#230]
Bonjour plusieurs fois j'ai installé arch je suis un un pc portable avec deux cartes graphiques je n'arrive pas a faire fonctionner la deuxième carte graphique NVIDIA il prend en compte que la intel même avec les choix NVIDIA a l'installation, quand je désactive la intel dans le bios j'ai aucune image mais sur un écran externe sa marche
Vous avez pas une astuce pour faire fonctionner les deux cartes graphiques en même temps sur arch ?
Cordialement

**Comment by Cardiacman13** [comment]
Je t'ai fais une vidéo : https://www.youtube.com/watch?v=GhsP6btpiiw

**Comment by Kadnix** [comment]
Franchement parfait je te remercie beaucoup je viens juste d'avoir la
notification pour la vidéo en plus sur YouTube
Un grand merci pour tout ce que tu fais franchement ta chaîne nickel rien à
dire je viens juste de débuter sur arch c'est tellement bien expliqué que
ça va tout seul
Encore merci
