### ISSUE TITLE
Ne pas forcer la désinstallation de KDE Discover

### ISSUE THREAD

**Issue by walrus543** [Cardiacman13/Architect#241]
Bonjour,

Concernant la désinstallation forcée de Discover: https://github.com/Cardiacman13/Architect/blob/bbb9c937d2181b9df8f2d12d7088ea55d9d7c676/src/de/kde.sh#L32

Soit : `sudo pacman -Rdd --noconfirm discover`

`discover` faisant partie de [plasma-meta](https://archlinux.org/packages/extra/any/plasma-meta/), cela ne me semble pas une bonne idée de désinstaller uniquement ce paquet. Il sera réinstallé automatiquement lors de la prochaine mise à jour de `plasma-meta`.

`plasma-meta` dépend **aujourd'hui** de :
````
bluedevil  drkonqi  kde-gtk-config  kdeplasma-addons  khotkeys  kinfocenter  kscreen
ksshaskpass  kwrited  oxygen  oxygen-sounds  plasma-browser-integration  plasma-desktop
plasma-disks  plasma-firewall  plasma-nm  plasma-workspace-wallpapers  plasma-pa
plasma-systemmonitor  plasma-thunderbolt  plasma-vault  plasma-welcome  kwayland-integration
kwallet-pam  kgamma  sddm-kcm  breeze-gtk  powerdevil  discover  xdg-desktop-portal-kde
````

La meilleure solution serait plutôt de désinstaller `plasma-meta` puis de casser les dépendances avec tous les paquets ci-dessus via `sudo pacman -D --asexplicit bluedevil...`
Mais que se passera-t-il le jour où une nouvelle dépendance sera ajoutée dans `plasma-meta` ? Ou si une dépendance est remplacée, ce qui pourrait un conflit ?

Je doute que le jeu en vale la chandelle. Mieux vaut laisser `discover` installé avec tout le reste.

**Comment by Cardiacman13** [comment]
Bonjour, 

Tu as raison, si la modif te vas je clos l'issue : https://github.com/Cardiacman13/Architect/commit/31d22a776a079edd8842d8eb9beb7625e937cf08

**Comment by walrus543** [comment]
Yep très bien 👍

**Comment by walrus543** [comment]
Raison supplémentaire de ne pas le supprimer : les mises à jour des thèmes/plugins
Exemple d'une discussion sur le sujet : https://www.reddit.com/r/kde/comments/v8m1ig/is_discover_necessary_on_arch/

Je n'utilise Discover que pour ça.
