### ISSUE TITLE
Snap support installation

### ISSUE THREAD

**Issue by Frizrat** [Cardiacman13/Architect#244]
Add snap
```
source src/cmd.sh

function support_snap() {
    install_one snapd
    exec_log "sudo systemctl enable snapd --now" "enable snap"
    exec_log "sudo systemctl enable snapd.apparmor --now" "start snap applications"
    exec_log "sudo ln -s /var/lib/snapd/snap /snap" "add classic snap support"
}
```

**Comment by Cardiacman13** [comment]
While I appreciate your suggestion to add Snap support to the script, I've intentionally chosen not to include it, as I believe it may not align with the design goals, and I find it unnecessary specifically for Arch Linux. I'm open to discussing this decision in a more comprehensive manner if you'd like. Feel free to share your thoughts in the [designated space](https://github.com/Cardiacman13/Architect/discussions), and we can have a constructive conversation about it. However, please understand that it's not considered an issue but rather a deliberate design choice.
