### ISSUE TITLE
Paccache.timer does not exist.

### ISSUE THREAD

**Issue by FRibadeau** [Cardiacman13/Architect#245]
Hello guys,

I just (now) created a new fresh Arch Linux virtual machine:

- Proxmox
- New VM
- Last Arch ISO
- archinstall
- architect.sh

In this script, I get an error when trying to enable the paccache service:
```Failed to enable unit: Unit file paccache.timer does not exist.```

After the script final reboot, the command ```systemctl enable --now paccache.timer``` runs without any error.

To double-check, I did it again (whole process described above: New VM...), I got the same error in the script.

Is this a bug of the script? Or of archinstall? Or ???

Thanks for your help,
Fred

**Comment by Skythrew** [comment]
Fixed with #246 :+1:
