### ISSUE TITLE
Barre de progression nécessaire

### ISSUE THREAD

**Issue by rficasa** [Cardiacman13/Architect#48]
le script se fait mais je trouve pas ça très intuitif de devoir juste "attendre" entre les étapes
les barres de progression te montre que ça tourne derrière
là on ne sait pas trop si ça a planté ou si ça tourne

**Comment by Cardiacman13** [comment]
On va voir, pour le moment on va faire une pause sur l'ajout de fonction. Temporairement on a ajouté "très long" ou "long" à coté des taches les plus longues pour que les gens ne s'inquiètent pas trop.

**Comment by Cardiacman13** [comment]
On a fait un paquets d'améliorations qui font que normalement ce n'est plus utile, entre autres : 
- Améliorer la commande reflector en début de script
- Ajouté devant les taches qui peuvent prendre du temps qu'elles seront potentiellement longue
- Enlever CUDA qui de toute façon ne sert pas à 99% des personnes

Si tu peux re tester et me donner ton avis, je veux bien ton retour :)

**Comment by Cardiacman13** [comment]
À revoir, c'est trop embêtant pour certains qui ont une faible connexion. Trouver une solution.
